### ISSUE TITLE
[FEATURE] FAQ Page

### ISSUE THREAD

**Issue by dharabor** [ShortestPathLab/MAPF-benchmark-web#15]
I think we need a catch-all page for common topics that could come up. For example:

Q: I did not receive credit for all of my submitted results!
A. We validate all submissions for feasibility and reject any which are invalid. If you submit a best-known solution and the corresponding plan is invalid we will not record any data for this problem. 

Q. The number of claimed lower-bounds for my submission has gone down since it was accepted. 
A. We compare lower-bound claims against best-known solutions. If your lower-bound claim X is contradicted by a feasible solution with cost Y < X, your claim is invalid and will be removed. In case of such errors we remove **all** LB claims of the associated submission.

Q. Is there a convenient method to download all of this data?
A. Yes! Please visit our download page at [link-goes-here].

Q. I found a problem with the data or the website.
A. Please raise an issue in our issue tracker. Describe the problem with as much detail as possible, and the steps leading up to the problem, so that we can reproduce it.

**Comment by bshen95** [comment]
Added a FAQ panel under the contribute, we may want to move this to an independent page if the list become too long.
